package Formas.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Circulo = 0;
  public static final int Forma = 1;
  public static final int Quadrado = 2;
  public static final int Retangulo = 3;
  public static final int Tela = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xcfcce30891bf49ebL, 0x913633dbfb422915L);
    builder.put(0x4679867c3218a831L, Circulo);
    builder.put(0x4679867c3218a830L, Forma);
    builder.put(0x4679867c3218a83bL, Quadrado);
    builder.put(0x5b8dfe967e7725b6L, Retangulo);
    builder.put(0x4679867c3218a845L, Tela);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
