package Formas.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Circulo_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Quadrado_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Retangulo_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Tela_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xcfcce30891bf49ebL, 0x913633dbfb422915L, 0x4679867c3218a831L), MetaIdFactory.conceptId(0xcfcce30891bf49ebL, 0x913633dbfb422915L, 0x4679867c3218a83bL), MetaIdFactory.conceptId(0xcfcce30891bf49ebL, 0x913633dbfb422915L, 0x5b8dfe967e7725b6L), MetaIdFactory.conceptId(0xcfcce30891bf49ebL, 0x913633dbfb422915L, 0x4679867c3218a845L)).seal();
}
